// Auto-generated from xlsx and csv
pub const JURADOS: &[(&str, &str)] = &[
    ("alluna@ipn.mx", "ANA LILIA LUNA GARCIA"),
    ("gchavezr@ipn.mx", "GIACOMO  CHAVEZ  ROMARO"),
    ("vagustin@ipn.mx", "VER�NICA  AGUST�N DOM�NGUEZ"),
    ("adgomezv@ipn.mx", "ADRIANA G�MEZ V�ZQUEZ"),
    ("karina.garciaj@aefcm.gob.mx", "KARINA  GARC�A JU�REZ"),
    ("ejimenezr@ipn.mx", "ERIKA JIM�NEZ  ROJAS"),
    (
        "francisca.callejas@aefc.gob.mx",
        "FRANCISCA SUSANA CALLEJAS �NGELES",
    ),
    ("mavilar@ipn.mx", "MILTON AVILA ROJAS"),
    ("bgutierreza@ipn.mx", "BRENDA GUTI�RREZ ALEM�N"),
    ("amorenoc@ipn.mx", "AXEL ERNESTO MORENO CERVANTES"),
    ("aiperezg@ipn.mx", "ARCELIA ILEANA  P�REZ GARC�A"),
    ("lsanchezne@ipn.mx", "LIZETH  S�NCHEZ NERIA"),
    ("cparedesm@ipn.mx", "CARMEN PATRICIA PAREDES MARROQUIN"),
    ("falvaa@ipn.mx", "FELIPE ANTONIO DE JES�S ALVA ALCALDE"),
    ("jlopezi@ipn.mx", "JOS� ALBERTO  L�PEZ  ISLAS"),
];

pub const PROTOTIPOS: &[(&str, &str, &str)] = &[
    ("DES015", "Objetos perdidos", "desarrollo-software"),
    ("DES021", "Sicsa", "desarrollo-software"),
    ("DES010", "Drive Awake", "desarrollo-software"),
    ("SOD004", "Eco-Rover", "soluciones-domesticas"),
    ("SOD025", "Alpha-Matrix", "soluciones-domesticas"),
    ("SOD036", "Lavaclean", "soluciones-domesticas"),
    ("SOD038", "Centro de lavado ecofriendly", "soluciones-domesticas"),
    ("SOD039", "\"STAR WASH\"", "soluciones-domesticas"),
    ("SOD018", "EcoRoof Electricity Tech", "soluciones-domesticas"),
    ("SOD019", "Ecosort", "soluciones-domesticas"),
    ("SOD020", "IBeePoli", "soluciones-domesticas"),
    ("SOD012", "SICAP", "soluciones-domesticas"),
    ("SOD022", "Smartdrop", "soluciones-domesticas"),
    ("SOD016", "SIMOV", "soluciones-domesticas"),
    ("SOD031", "AVVA", "soluciones-domesticas"),
    ("MEP002", "REFilament", "maquinaria-equipo"),
    ("MEP005", "Sistema de gestión de energía eléctrica inteligente adaptada para una sección del laboratorio de control númerico", "maquinaria-equipo"),
    ("MEP051", "TETRABLOCK", "maquinaria-equipo"),
    ("MEP014", "EcoBlast-X", "maquinaria-equipo"),
    ("MEP015", "Float Rescue", "maquinaria-equipo"),
    ("MEP016", "Resqcar", "maquinaria-equipo"),
    ("MEP030", "CNC SOWING ROBOT", "maquinaria-equipo"),
    ("MEP007", "BEMS dual", "maquinaria-equipo"),
    ("MEP039", "DBR (Dron de Búsqueda y Rescate)", "maquinaria-equipo"),
    ("MEP040", "H.S.S (Hiking Search Spider)", "maquinaria-equipo"),
    ("MEP004", "Vulcan Grip", "maquinaria-equipo"),
    ("MEP033", "Cortadora de tubos PVC", "maquinaria-equipo"),
    ("MEP036", "Bachito", "maquinaria-equipo"),
    ("MEP024", "Sistema automatizado de bebidas personalizables", "maquinaria-equipo"),
    ("MEP008", "Xpendelectronics", "maquinaria-equipo"),
    ("MEP035", "V.E.S.T.A.", "maquinaria-equipo"),
    ("PPS028", "Lunéva", "productos-salud"),
    ("PPS009", "Fewgaz", "productos-salud"),
    ("PPS004", "Robot de reanimación cardiopulmonar", "productos-salud"),
    ("PPS022", "CAPSI-MUSCLE", "productos-salud"),
    ("PPS008", "MOLDER", "productos-salud"),
    ("PPS021", "SENTINEL", "productos-salud"),
    ("PPS013", "Tochka", "productos-salud"),
    ("PPS001", "AloeCare", "productos-salud"),
    ("PPS010", "Pastillero Electrónico Inteligente", "productos-salud"),
    ("PPS015", "Biowave Bioplástico Sustentable de Origen Vegetal", "productos-salud"),
    ("PPS003", "LYRA", "productos-salud"),
    ("PRE001", "Conectando Manos", "productos-ensenanza"),
    ("PRE005", "Bichoexplora", "productos-ensenanza"),
    ("PRE006", "Arcade Teen", "productos-ensenanza"),
    ("PRE010", "LookBioGAO", "productos-ensenanza"),
    ("PRE025", "Túnel de viento para probar la aerodinámica de carrocerías", "productos-ensenanza"),
    ("PRE012", "(SiMeTec)", "productos-ensenanza"),
    ("PRE007", "Libreta verde \"Cuak Organic\"", "productos-ensenanza"),
    ("PRE022", "RoboDidact", "productos-ensenanza"),
    ("PRE015", "Agenda wellness bienestar", "productos-ensenanza"),
    ("PRE030", "CodeSpark", "productos-ensenanza"),
    ("PRE026", "Sembrando ideas politécnicas", "productos-ensenanza"),
    ("PRE009", "Roboactives", "productos-ensenanza"),
    ("PRE011", "Manual del buen conductor", "productos-ensenanza"),
    ("PRE021", "Teclado de Articulos", "productos-ensenanza"),
    ("PQB001", "Bateria de Al para situaciones emergentes", "procesos-quimicos-biologicos"),
    ("PQB004", "ZIVA", "procesos-quimicos-biologicos"),
    ("PQB005", "Celestallow", "procesos-quimicos-biologicos"),
    ("PQB006", "ZESTRA", "procesos-quimicos-biologicos"),
    ("PQB008", "Prototipo automatizado para compostaje de residuos orgánicos", "procesos-quimicos-biologicos"),
    ("PQB009", "Chikawitas", "procesos-quimicos-biologicos"),
    ("PQB013", "BIOPLASTIC-PACK", "procesos-quimicos-biologicos"),
    ("PQB015", "nutriPOP", "procesos-quimicos-biologicos"),
    ("PQB017", "LU'UM", "procesos-quimicos-biologicos"),
    ("PQB018", "Sunleaf (hojas de papel con cascara de naranja)", "procesos-quimicos-biologicos"),
    ("PQB010", "Sistema De Purificación Automatizado De Agua Pluvial Con Monitoreo Remoto", "procesos-quimicos-biologicos"),
    ("PQB012", "PHYO", "procesos-quimicos-biologicos"),
    ("APE011", "ROBOT PAINNT", "aplicacion-empresa"),
    ("APE013", "Centrifugadora de Textiles", "aplicacion-empresa"),
];
